from django.urls import path
from . import views 

urlpatterns = [
    path('register', views.welcome, name='welcome'),
    path('new-welcome', views.new_welcome, name='new_welcome'),
    path('register/<str:role>', views.register_by_role, name='register_by_role'),
    path('save/customer', views.save_user, name='save_user'),
    path('save/ngo', views.save_ngo, name='save_ngo'),
    path('login', views.login_page, name='login_page'),
    path('auth/login', views.login_auth, name='login_auth'),
    path('auth/login-old', views.login_auth_OLD, name='login_auth_old'),
    path('save/advertiser', views.save_advertiser, name='save_advertiser'),
    path('save/client', views.save_client, name='save_client'),
    path('save/medical_pharmacy', views.save_medical_pharmacy, name='save_pharmacy'),        
    path("otp/send", views.send_otp, name="send_otp"),
    path("otp/verify", views.verify_otp, name="verify_otp"),
    path('forgot-password', views.forgot_password, name='forgot_password'),
    path("reset-password/<str:token>/", views.reset_password, name="reset_password"),
    path("save/lab", views.save_lab, name="save_lab"),
    path("save/doctor", views.save_doctor, name="save_doctor"),
    path("save/hospital", views.save_hospital, name="save_hospital"),
    path('file-scan/',views.file_scan_api,name='file_scan'),
    path("send-contact-person-otp/",views.send_contact_person_otp,name="send_contact_person_otp",),
    path("new-signin/", views.new_signin, name="new_signin"),
    path("new-otp-verify/", views.new_otp_verify, name="new_otp_verify"),
    path("new-signup/", views.new_signup, name="new_signup"),
    path("new-kyc/", views.new_kyc, name="new_kyc"),
    path("profile-verification/", views.profile_verification, name="profile_verification"),
    path("profile-review/", views.profile_review, name="profile_review"),
    path("doctor-verification/", views.doctor_verification, name="doctor_verification"),
    path("lab-verification/", views.lab_verification, name="lab_verification"),
    path("pharmacy-verification/", views.pharmacy_verification, name="pharmacy_verification"),
    path('check-phone', views.check_phone, name='check_phone'),
    path('auth/verify-login-otp', views.verify_login_otp, name='verify_login_otp'),
]
