# Generated by Django 4.2.21 on 2025-06-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_email_notifications_user_inapp_notifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountSubscriptionFAQ',
        ),
    ]
